version: '2'
services:
    jhipsterelasticsearch-app:
        image: jhipsterelasticsearch
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterelasticsearch-postgresql:5432/jhipsterElasticsearch
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipsterelasticsearch-elasticsearch:9300
        ports:
            - 8080:8080
    jhipsterelasticsearch-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterelasticsearch-postgresql
    jhipsterelasticsearch-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipsterelasticsearch-elasticsearch
